#!/usr/bin/env ruby

=begin

	@title	Anlisis Lexicográfico del interpretador para el lenguaje Lanscii

	@author	Richard Lares 11-10508
	@author	Oscar Guillen 11-11264

	@description Código fuente del análisis lexicográfico para el interpretador de Lanscii

=end

# Lectura del contenido del archivo de entrada
require './lexer.rb'

l=lexer()