#!/usr/bin/env ruby

=begin

	@title	Análisis Sintáctico del interpretador para el lenguaje Lanscii

	@author	Richard Lares 11-10508
	@author	Oscar Guillen 11-11264

	@description Código fuente del análisis sintáctico para el interpretador de Lanscii

=end

require './class'
require './lexer'
require './parser'

l=Lexer.new(ARGV[0])
if l.matching
	#print t
	#puts ""
	p=Parser.new
	variable=p.parse(l.get_token)
else
	puts l.get_token
end
variable.to_s(0)