#!/usr/bin/env ruby

=begin

	@title	Análisis Sintáctico del interpretador para el lenguaje Lanscii

	@author	Richard Lares 11-10508
	@author	Oscar Guillen 11-11264

	@description Código fuente del análisis sintáctico para el interpretador de Lanscii

=end

require './class'
require './lexer'
require './parser'

l=Lexer.new(ARGV[0]) 				# Se crea el lexer

if l.matching						# Si no hubo errores lexicográficos, 
									# se procede con el análisis sintáctico del archivo
									
	p=Parser.new					# Se crea el parser
	variable=p.parse(l.get_token)	# Se parsea el arreglo de tokens
	variable.to_s					# Se imprime el árbol generado por el parser

else								# Si hubo errores lexicográficos, se imprimen
	puts l.get_token
end