#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.8
# from Racc grammer file "".
#

require 'racc/parser.rb'
class LansciiParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     2,     2,     2,    10,     7,     3,     3,     3,     5,     8,
     6,    11,     4,    13 ]

racc_action_check = [
     0,    10,     6,     8,     4,     0,    10,     6,     2,     5,
     2,     9,     1,    12 ]

racc_action_pointer = [
    -2,    12,     5,   nil,     4,     5,     0,   nil,    -2,     5,
    -1,   nil,     7,   nil ]

racc_action_default = [
    -4,    -4,    -4,    -3,    -4,    -4,    -4,    14,    -4,    -4,
    -4,    -2,    -4,    -1 ]

racc_goto_table = [
     1,   nil,   nil,   nil,   nil,   nil,     9,   nil,   nil,   nil,
    12 ]

racc_goto_check = [
     1,   nil,   nil,   nil,   nil,   nil,     1,   nil,   nil,   nil,
     1 ]

racc_goto_pointer = [
   nil,     0 ]

racc_goto_default = [
   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  6, 9, :_reduce_none,
  4, 9, :_reduce_none,
  1, 9, :_reduce_none ]

racc_reduce_n = 4

racc_shift_n = 14

racc_token_table = {
  false => 0,
  :error => 1,
  "{" => 2,
  :D => 3,
  "|" => 4,
  :I => 5,
  "}" => 6,
  "Listo" => 7 }

racc_nt_base = 8

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"{\"",
  "D",
  "\"|\"",
  "I",
  "\"}\"",
  "\"Listo\"",
  "$start",
  "S" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class LansciiParser
