#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'
class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 91)

def parse(t)
	@lexer=t
	do_parse
end

def next_token
	@lexer.shift
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     2,     6,     7,     8,    69,     2,    22,    11,    12,    19,
    15,    20,    11,    12,    16,    15,    20,     2,    26,    16,
     6,     7,     8,    20,    11,    12,     2,    15,    25,    99,
    22,    16,    27,    11,    12,    22,    15,     9,     2,    50,
    16,    20,     9,     2,    50,    11,    12,    92,    15,    22,
    11,    12,    16,    15,     9,    48,    49,    16,     2,    20,
    48,    49,    98,     9,    20,    11,    12,    68,    15,     2,
   102,    18,    16,    17,    50,     9,    11,    12,     3,    15,
     9,     2,    93,    16,    50,   nil,   nil,    58,    46,    47,
    48,    49,    51,    52,    53,     9,   nil,   nil,    46,    47,
    48,    49,    51,    52,    53,    62,     9,    54,    55,    56,
    57,    59,    60,    61,   100,    62,    50,    20,   nil,    58,
    90,    91,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    46,    47,    48,    49,    51,    52,    53,   nil,    50,    54,
    55,    56,    57,    59,    60,    61,    66,    62,    50,   nil,
   nil,    58,    46,    47,    48,    49,    51,    52,    53,   nil,
   nil,    67,    46,    47,    48,    49,    51,    52,    53,    62,
    50,    54,    55,    56,    57,    59,    60,    61,    50,    62,
   nil,    58,   nil,   nil,    46,    47,    48,    49,    51,   nil,
    53,   nil,    46,    47,    48,    49,    51,    52,    53,    50,
   nil,   -47,   -47,   -47,   -47,    59,    60,    61,    50,    62,
   nil,    58,   nil,    46,    47,    48,    49,    51,    52,    53,
   nil,    94,    46,    47,    48,    49,    51,    52,    53,    50,
    62,    54,    55,    56,    57,    59,    60,    61,    50,    62,
   nil,    58,   nil,    46,    47,    48,    49,   nil,   nil,    53,
   nil,   nil,    46,    47,    48,    49,    51,    52,    53,   nil,
   nil,   -47,   -47,   -47,   -47,    59,    60,    61,    50,    62,
   nil,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    46,    47,    48,    49,    51,    52,    53,   nil,
   nil,   -47,   -47,   -47,   -47,    59,    60,    61,    50,    62,
   nil,    58,   nil,   nil,   nil,   nil,    45,   nil,   nil,   nil,
   nil,   nil,    46,    47,    48,    49,    51,    52,    53,   nil,
   nil,    54,    55,    56,    57,    59,    60,    61,    50,    62,
   nil,    58,   nil,   nil,   nil,   nil,   nil,    86,   nil,   nil,
   nil,   nil,    46,    47,    48,    49,    51,    52,    53,   nil,
   nil,    54,    55,    56,    57,    59,    60,    61,    50,    62,
   nil,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    46,    47,    48,    49,    51,    52,    53,    50,
   nil,   nil,    58,   nil,   nil,    59,    60,    61,   nil,    62,
   nil,   nil,   nil,    46,    47,    48,    49,    51,    52,    53,
   nil,   nil,   -47,   -47,   -47,   -47,    59,    60,    61,    50,
    62,   nil,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    46,    47,    48,    49,    51,    52,    53,
    50,   nil,   nil,    58,   nil,   nil,    59,    60,    61,   nil,
    62,   nil,   nil,   nil,    46,    47,    48,    49,    51,    52,
    53,   nil,    32,    54,    55,    56,    57,    59,    60,    61,
    31,    62,   nil,   nil,   nil,   nil,    33,    34,    32,   nil,
   nil,   nil,   nil,   nil,   nil,    35,    31,    36,    37,    29,
    30,   nil,    33,    34,    32,   nil,   nil,   nil,   nil,   nil,
   nil,    35,    31,    36,    37,    29,    30,   nil,    33,    34,
    32,   nil,   nil,   nil,   nil,   nil,   nil,    35,    31,    36,
    37,    29,    30,   nil,    33,    34,    32,   nil,   nil,   nil,
   nil,   nil,   nil,    35,    31,    36,    37,    29,    30,   nil,
    33,    34,    32,   nil,   nil,   nil,   nil,   nil,   nil,    35,
    31,    36,    37,    29,    30,   nil,    33,    34,    32,   nil,
   nil,   nil,   nil,   nil,   nil,    35,    31,    36,    37,    29,
    30,   nil,    33,    34,    32,   nil,   nil,   nil,   nil,   nil,
   nil,    35,    31,    36,    37,    29,    30,   nil,    33,    34,
    32,   nil,   nil,   nil,   nil,   nil,   nil,    35,    31,    36,
    37,    29,    30,   nil,    33,    34,    32,   nil,   nil,   nil,
   nil,   nil,   nil,    35,    31,    36,    37,    29,    30,   nil,
    33,    34,    32,   nil,   nil,   nil,   nil,   nil,   nil,    35,
    31,    36,    37,    29,    30,   nil,    33,    34,    32,   nil,
   nil,   nil,   nil,   nil,   nil,    35,    31,    36,    37,    29,
    30,   nil,    33,    34,    32,   nil,   nil,   nil,   nil,   nil,
   nil,    35,    31,    36,    37,    29,    30,   nil,    33,    34,
    32,   nil,   nil,   nil,   nil,   nil,   nil,    35,    31,    36,
    37,    29,    30,   nil,    33,    34,    32,   nil,   nil,   nil,
   nil,   nil,   nil,    35,    31,    36,    37,    29,    30,   nil,
    33,    34,    32,   nil,   nil,   nil,   nil,   nil,   nil,    35,
    31,    36,    37,    29,    30,   nil,    33,    34,    32,   nil,
   nil,   nil,   nil,   nil,   nil,    35,    31,    36,    37,    29,
    30,   nil,    33,    34,    32,   nil,   nil,   nil,   nil,   nil,
   nil,    35,    31,    36,    37,    29,    30,   nil,    33,    34,
    32,   nil,   nil,   nil,   nil,   nil,   nil,    35,    31,    36,
    37,    29,    30,   nil,    33,    34,    32,   nil,   nil,   nil,
   nil,   nil,   nil,    35,    31,    36,    37,    29,    30,   nil,
    33,    34,    32,   nil,   nil,   nil,   nil,   nil,   nil,    35,
    31,    36,    37,    39,    30,   nil,    33,    34,    32,   nil,
   nil,   nil,   nil,   nil,   nil,    35,    31,    36,    37,    29,
    30,   nil,    33,    34,    32,   nil,   nil,   nil,   nil,   nil,
   nil,    35,    31,    36,    37,    29,    30,   nil,    33,    34,
    32,   nil,   nil,   nil,   nil,   nil,   nil,    35,    31,    36,
    37,    29,    30,   nil,    33,    34,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    35,   nil,    36,    37,    29,    30 ]

racc_action_check = [
   100,    22,    22,    22,    40,    66,     7,   100,   100,     5,
   100,    40,    66,    66,   100,    66,     5,     2,    11,    66,
     2,     2,     2,    96,     2,     2,    18,     2,     9,    96,
     8,     2,    12,    18,    18,    22,    18,   100,    45,    72,
    18,    87,    66,    91,    71,    45,    45,    87,    45,     6,
    91,    91,    45,    91,     2,    72,    72,    91,    93,    95,
    71,    71,    95,    18,   101,    93,    93,    39,    93,    20,
   101,     4,    93,     3,    84,    45,    20,    20,     1,    20,
    91,     0,    88,    20,    88,   nil,   nil,    88,    84,    84,
    84,    84,    84,    84,    84,    93,   nil,   nil,    88,    88,
    88,    88,    88,    88,    88,    84,    20,    88,    88,    88,
    88,    88,    88,    88,    97,    88,    97,    70,   nil,    97,
    70,    70,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    97,    97,    97,    97,    97,    97,    97,   nil,    65,    97,
    97,    97,    97,    97,    97,    97,    38,    97,    38,   nil,
   nil,    38,    65,    65,    65,    65,    65,    65,    65,   nil,
   nil,    38,    38,    38,    38,    38,    38,    38,    38,    65,
    77,    38,    38,    38,    38,    38,    38,    38,    78,    38,
   nil,    78,   nil,   nil,    77,    77,    77,    77,    77,   nil,
    77,   nil,    78,    78,    78,    78,    78,    78,    78,    85,
   nil,    78,    78,    78,    78,    78,    78,    78,    89,    78,
   nil,    89,   nil,    85,    85,    85,    85,    85,    85,    85,
   nil,    89,    89,    89,    89,    89,    89,    89,    89,    76,
    85,    89,    89,    89,    89,    89,    89,    89,    79,    89,
   nil,    79,   nil,    76,    76,    76,    76,   nil,   nil,    76,
   nil,   nil,    79,    79,    79,    79,    79,    79,    79,   nil,
   nil,    79,    79,    79,    79,    79,    79,    79,    80,    79,
   nil,    80,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    80,    80,    80,    80,    80,    80,    80,   nil,
   nil,    80,    80,    80,    80,    80,    80,    80,    28,    80,
   nil,    28,   nil,   nil,   nil,   nil,    28,   nil,   nil,   nil,
   nil,   nil,    28,    28,    28,    28,    28,    28,    28,   nil,
   nil,    28,    28,    28,    28,    28,    28,    28,    64,    28,
   nil,    64,   nil,   nil,   nil,   nil,   nil,    64,   nil,   nil,
   nil,   nil,    64,    64,    64,    64,    64,    64,    64,   nil,
   nil,    64,    64,    64,    64,    64,    64,    64,    83,    64,
   nil,    83,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    83,    83,    83,    83,    83,    83,    83,    81,
   nil,   nil,    81,   nil,   nil,    83,    83,    83,   nil,    83,
   nil,   nil,   nil,    81,    81,    81,    81,    81,    81,    81,
   nil,   nil,    81,    81,    81,    81,    81,    81,    81,    82,
    81,   nil,    82,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    82,    82,    82,    82,    82,    82,    82,
    44,   nil,   nil,    44,   nil,   nil,    82,    82,    82,   nil,
    82,   nil,   nil,   nil,    44,    44,    44,    44,    44,    44,
    44,   nil,    47,    44,    44,    44,    44,    44,    44,    44,
    47,    44,   nil,   nil,   nil,   nil,    47,    47,    35,   nil,
   nil,   nil,   nil,   nil,   nil,    47,    35,    47,    47,    47,
    47,   nil,    35,    35,    46,   nil,   nil,   nil,   nil,   nil,
   nil,    35,    46,    35,    35,    35,    35,   nil,    46,    46,
    55,   nil,   nil,   nil,   nil,   nil,   nil,    46,    55,    46,
    46,    46,    46,   nil,    55,    55,    48,   nil,   nil,   nil,
   nil,   nil,   nil,    55,    48,    55,    55,    55,    55,   nil,
    48,    48,    49,   nil,   nil,   nil,   nil,   nil,   nil,    48,
    49,    48,    48,    48,    48,   nil,    49,    49,    50,   nil,
   nil,   nil,   nil,   nil,   nil,    49,    50,    49,    49,    49,
    49,   nil,    50,    50,    51,   nil,   nil,   nil,   nil,   nil,
   nil,    50,    51,    50,    50,    50,    50,   nil,    51,    51,
    52,   nil,   nil,   nil,   nil,   nil,   nil,    51,    52,    51,
    51,    51,    51,   nil,    52,    52,    54,   nil,   nil,   nil,
   nil,   nil,   nil,    52,    54,    52,    52,    52,    52,   nil,
    54,    54,    32,   nil,   nil,   nil,   nil,   nil,   nil,    54,
    32,    54,    54,    54,    54,   nil,    32,    32,    56,   nil,
   nil,   nil,   nil,   nil,   nil,    32,    56,    32,    32,    32,
    32,   nil,    56,    56,    57,   nil,   nil,   nil,   nil,   nil,
   nil,    56,    57,    56,    56,    56,    56,   nil,    57,    57,
    58,   nil,   nil,   nil,   nil,   nil,   nil,    57,    58,    57,
    57,    57,    57,   nil,    58,    58,    59,   nil,   nil,   nil,
   nil,   nil,   nil,    58,    59,    58,    58,    58,    58,   nil,
    59,    59,    60,   nil,   nil,   nil,   nil,   nil,   nil,    59,
    60,    59,    59,    59,    59,   nil,    60,    60,    94,   nil,
   nil,   nil,   nil,   nil,   nil,    60,    94,    60,    60,    60,
    60,   nil,    94,    94,    31,   nil,   nil,   nil,   nil,   nil,
   nil,    94,    31,    94,    94,    94,    94,   nil,    31,    31,
    25,   nil,   nil,   nil,   nil,   nil,   nil,    31,    25,    31,
    31,    31,    31,   nil,    25,    25,    16,   nil,   nil,   nil,
   nil,   nil,   nil,    25,    16,    25,    25,    25,    25,   nil,
    16,    16,    67,   nil,   nil,   nil,   nil,   nil,   nil,    16,
    67,    16,    16,    16,    16,   nil,    67,    67,    68,   nil,
   nil,   nil,   nil,   nil,   nil,    67,    68,    67,    67,    67,
    67,   nil,    68,    68,    15,   nil,   nil,   nil,   nil,   nil,
   nil,    68,    15,    68,    68,    68,    68,   nil,    15,    15,
    61,   nil,   nil,   nil,   nil,   nil,   nil,    15,    61,    15,
    15,    15,    15,   nil,    61,    61,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    61,   nil,    61,    61,    61,    61 ]

racc_action_pointer = [
    79,    78,    15,    73,    68,     5,    10,   -33,    -9,    20,
   nil,   -21,    -7,   nil,   nil,   792,   744,   nil,    24,   nil,
    67,   nil,    -4,   nil,   nil,   728,   nil,   nil,   293,   nil,
   nil,   712,   600,   nil,   nil,   456,   nil,   nil,   143,    52,
     0,   nil,   nil,   nil,   425,    36,   472,   440,   504,   520,
   536,   552,   568,   nil,   584,   488,   616,   632,   648,   664,
   680,   808,   nil,   nil,   323,   133,     3,   760,   776,   nil,
   106,    39,    34,   nil,   nil,   nil,   224,   165,   173,   233,
   263,   374,   404,   353,    69,   194,   nil,    30,    79,   203,
   nil,    41,   nil,    56,   696,    48,    12,   111,   nil,   nil,
    -2,    53,   nil ]

racc_action_default = [
   -47,   -47,   -47,   -47,   -47,   -47,   -47,   -47,   -47,   -47,
   -10,   -47,   -47,   -13,   -14,   -47,   -47,   103,   -47,    -2,
   -47,    -3,    -8,    -4,    -5,   -47,   -11,   -12,   -47,   -21,
   -22,   -47,   -47,   -33,   -34,   -47,   -45,   -46,   -47,   -21,
   -47,   -15,    -6,    -7,    -9,   -47,   -47,   -47,   -47,   -47,
   -47,   -47,   -47,   -32,   -47,   -47,   -47,   -47,   -47,   -47,
   -47,   -47,   -44,   -28,   -47,   -43,   -47,   -47,   -47,    -1,
   -47,   -23,   -24,   -25,   -26,   -27,   -30,   -31,   -35,   -36,
   -37,   -38,   -39,   -40,   -41,   -42,   -29,   -47,   -47,   -47,
   -16,   -47,   -18,   -47,   -47,   -47,   -47,   -47,   -17,   -19,
   -47,   -47,   -20 ]

racc_goto_table = [
     5,     1,   nil,     4,   nil,    28,    38,   nil,    21,    23,
    24,   nil,   nil,   nil,   nil,    44,    40,   nil,    41,   nil,
   nil,    63,    64,    43,    42,    65,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    71,    72,    73,    74,
    75,    76,    77,    70,    78,    79,    80,    81,    82,    83,
    84,    85,   nil,   nil,   nil,   nil,   nil,    88,    89,   nil,
   nil,   nil,   nil,   nil,    87,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    97,   nil,   nil,   nil,   nil,    95,
   nil,    96,   nil,   nil,   nil,   nil,   nil,   nil,   101 ]

racc_goto_check = [
     3,     1,   nil,     2,   nil,     5,     5,   nil,     4,     4,
     4,   nil,   nil,   nil,   nil,     5,     3,   nil,     3,   nil,
   nil,     5,     5,     2,     4,     5,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     5,     5,     5,     5,
     5,     5,     5,     3,     5,     5,     5,     5,     5,     5,
     5,     5,   nil,   nil,   nil,   nil,   nil,     5,     5,   nil,
   nil,   nil,   nil,   nil,     3,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     5,   nil,   nil,   nil,   nil,     3,
   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,     1,     1,    -2,     2,   -10,   nil,   nil ]

racc_goto_default = [
   nil,    10,   nil,   nil,   nil,   nil,    13,    14 ]

racc_reduce_table = [
  0, 0, :racc_error,
  5, 43, :_reduce_1,
  3, 43, :_reduce_2,
  2, 44, :_reduce_3,
  2, 44, :_reduce_4,
  2, 44, :_reduce_5,
  2, 46, :_reduce_6,
  2, 46, :_reduce_7,
  1, 46, :_reduce_8,
  3, 45, :_reduce_9,
  1, 45, :_reduce_10,
  2, 45, :_reduce_11,
  2, 45, :_reduce_12,
  1, 45, :_reduce_13,
  1, 45, :_reduce_14,
  3, 45, :_reduce_15,
  5, 48, :_reduce_16,
  7, 48, :_reduce_17,
  5, 49, :_reduce_18,
  7, 49, :_reduce_19,
  9, 49, :_reduce_20,
  1, 47, :_reduce_21,
  1, 47, :_reduce_22,
  3, 47, :_reduce_23,
  3, 47, :_reduce_24,
  3, 47, :_reduce_25,
  3, 47, :_reduce_26,
  3, 47, :_reduce_27,
  2, 47, :_reduce_none,
  3, 47, :_reduce_29,
  3, 47, :_reduce_30,
  3, 47, :_reduce_31,
  2, 47, :_reduce_32,
  1, 47, :_reduce_33,
  1, 47, :_reduce_34,
  3, 47, :_reduce_35,
  3, 47, :_reduce_36,
  3, 47, :_reduce_37,
  3, 47, :_reduce_38,
  3, 47, :_reduce_39,
  3, 47, :_reduce_40,
  3, 47, :_reduce_41,
  3, 47, :_reduce_42,
  2, 47, :_reduce_43,
  2, 47, :_reduce_44,
  1, 47, :_reduce_45,
  1, 47, :_reduce_46 ]

racc_reduce_n = 47

racc_shift_n = 103

racc_token_table = {
  false => 0,
  :error => 1,
  :LCURLY => 2,
  :PIPE => 3,
  :RCURLY => 4,
  :PERCENTAGE => 5,
  :EXCLAMATIONMARK => 6,
  :AT => 7,
  :EQUALS => 8,
  :READ => 9,
  :WRITE => 10,
  :SEMICOLON => 11,
  :LPARENTHESIS => 12,
  :QUESTIONMARK => 13,
  :RPARENTHESIS => 14,
  :COLON => 15,
  :LSQUARE => 16,
  :RSQUARE => 17,
  :DOUBLEDOT => 18,
  :PLUS => 19,
  :MINUS => 20,
  :TIMES => 21,
  :DIVIDE => 22,
  :AND => 23,
  :OR => 24,
  :NOT => 25,
  :TRUE => 26,
  :FALSE => 27,
  :LESS => 28,
  :LESSEQUAL => 29,
  :GREATER => 30,
  :GREATEREQUAL => 31,
  :NOTEQUAL => 32,
  :AMPERSAND => 33,
  :TILDE => 34,
  :DOLLAR => 35,
  :APOSTROPHE => 36,
  :CANVAS => 37,
  :EMPTYCANVAS => 38,
  :ID => 39,
  :NUM => 40,
  :UMINUS => 41 }

racc_nt_base = 42

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "LCURLY",
  "PIPE",
  "RCURLY",
  "PERCENTAGE",
  "EXCLAMATIONMARK",
  "AT",
  "EQUALS",
  "READ",
  "WRITE",
  "SEMICOLON",
  "LPARENTHESIS",
  "QUESTIONMARK",
  "RPARENTHESIS",
  "COLON",
  "LSQUARE",
  "RSQUARE",
  "DOUBLEDOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "AND",
  "OR",
  "NOT",
  "TRUE",
  "FALSE",
  "LESS",
  "LESSEQUAL",
  "GREATER",
  "GREATEREQUAL",
  "NOTEQUAL",
  "AMPERSAND",
  "TILDE",
  "DOLLAR",
  "APOSTROPHE",
  "CANVAS",
  "EMPTYCANVAS",
  "ID",
  "NUM",
  "UMINUS",
  "$start",
  "PROGRAM",
  "DECLARE",
  "BODY",
  "INSTR",
  "EXPR",
  "COND",
  "ITER" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 28)
  def _reduce_1(val, _values, result)
    return PROGRAM_DECLARE_BODY.new(val[1],val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 29)
  def _reduce_2(val, _values, result)
    return PROGRAM.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_3(val, _values, result)
    result = DECLARE_INT.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 33)
  def _reduce_4(val, _values, result)
    result = DECLARE_BOOL.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 34)
  def _reduce_5(val, _values, result)
    result = DECLARE_LIE.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_6(val, _values, result)
    result = MORE_INST.new(val[0],val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 38)
  def _reduce_7(val, _values, result)
    result = INST_DECLARE.new(val[0],val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 39)
  def _reduce_8(val, _values, result)
    result = INST_ID.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 42)
  def _reduce_9(val, _values, result)
    result = BODY_ASSIGN.new(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 43)
  def _reduce_10(val, _values, result)
    result = BODY.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 44)
  def _reduce_11(val, _values, result)
    result = BODY_READ.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 45)
  def _reduce_12(val, _values, result)
    result = BODY_WRITE.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 46)
  def _reduce_13(val, _values, result)
    result = BODY.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 47)
  def _reduce_14(val, _values, result)
    result = BODY.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_15(val, _values, result)
    result = BODIES.new(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 51)
  def _reduce_16(val, _values, result)
    result = IF_THEN.new(val[1],val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 52)
  def _reduce_17(val, _values, result)
    result = IF_THEN_ELSE.new(val[1],val[3],val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 55)
  def _reduce_18(val, _values, result)
    result = ONE_COND.new(val[1],val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 56)
  def _reduce_19(val, _values, result)
    result = COND.new(val[1],val[3],val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 57)
  def _reduce_20(val, _values, result)
    result = ID_COND.new(val[1],val[3],val[5],val[7])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 60)
  def _reduce_21(val, _values, result)
    result = EXP_ID.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_22(val, _values, result)
    result = EXP_NUM.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 62)
  def _reduce_23(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 63)
  def _reduce_24(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_25(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 65)
  def _reduce_26(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 66)
  def _reduce_27(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

# reduce 28 omitted

module_eval(<<'.,.,', 'parser.y', 68)
  def _reduce_29(val, _values, result)
    result = EXPR.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 69)
  def _reduce_30(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 70)
  def _reduce_31(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 71)
  def _reduce_32(val, _values, result)
    result = LEFT_EXPR.new(val[0],val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 72)
  def _reduce_33(val, _values, result)
    result = EXP_BOOL.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 73)
  def _reduce_34(val, _values, result)
    result = EXP_BOOL.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 74)
  def _reduce_35(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 75)
  def _reduce_36(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 76)
  def _reduce_37(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 77)
  def _reduce_38(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 78)
  def _reduce_39(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 79)
  def _reduce_40(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 80)
  def _reduce_41(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 81)
  def _reduce_42(val, _values, result)
    result = DOUBLE_EXPR.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 82)
  def _reduce_43(val, _values, result)
    result = RIGHT_EXPR.new(val[0],val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 83)
  def _reduce_44(val, _values, result)
    result = LEFT_EXPR.new(val[0],val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 84)
  def _reduce_45(val, _values, result)
    result = EXP_CANVAS.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 85)
  def _reduce_46(val, _values, result)
    result = EXP_CANVAS.new(val[0])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
